export const ACTIVITY_TYPES_LIST = 'ACTIVITY_TYPES_LIST';
export const ACTIVITY_TYPES_LIST_PENDING = 'ACTIVITY_TYPES_LIST_PENDING';
export const ACTIVITY_TYPES_LIST_FULFILLED = 'ACTIVITY_TYPES_LIST_FULFILLED';
export const ACTIVITY_TYPES_LIST_REJECTED = 'ACTIVITY_TYPES_LIST_REJECTED';

export const list = () => ({
    type: ACTIVITY_TYPES_LIST
});