    export const ACTIVITY_ASSIGNMENTS_BY_STUDENT = 'ACTIVITY_ASSIGNMENTS_BY_STUDENT';
export const ACTIVITY_ASSIGNMENTS_BY_STUDENT_PENDING = 'ACTIVITY_ASSIGNMENTS_BY_STUDENT_PENDING';
export const ACTIVITY_ASSIGNMENTS_BY_STUDENT_FULFILLED = 'ACTIVITY_ASSIGNMENTS_BY_STUDENT_FULFILLED';
export const ACTIVITY_ASSIGNMENTS_BY_STUDENT_REJECTED = 'ACTIVITY_ASSIGNMENTS_BY_STUDENT_REJECTED';

export const ACTIVITY_ASSIGNMENTS_BY_ID = 'ACTIVITY_ASSIGNMENTS_BY_ID';
export const ACTIVITY_ASSIGNMENTS_BY_ID_PENDING = 'ACTIVITY_ASSIGNMENTS_BY_ID_PENDING';
export const ACTIVITY_ASSIGNMENTS_BY_ID_FULFILLED = 'ACTIVITY_ASSIGNMENTS_BY_ID_FULFILLED';
export const ACTIVITY_ASSIGNMENTS_BY_ID_REJECTED = 'ACTIVITY_ASSIGNMENTS_BY_ID_REJECTED'; 

export const ACTIVITY_ASSIGNMENTS_SUBMIT = 'ACTIVITY_ASSIGNMENTS_SUBMIT';
export const ACTIVITY_ASSIGNMENTS_SUBMIT_PENDING = 'ACTIVITY_ASSIGNMENTS_SUBMIT_PENDING';
export const ACTIVITY_ASSIGNMENTS_SUBMIT_FULFILLED = 'ACTIVITY_ASSIGNMENTS_SUBMIT_FULFILLED';
export const ACTIVITY_ASSIGNMENTS_SUBMIT_REJECTED = 'ACTIVITY_ASSIGNMENTS_SUBMIT_REJECTED';

export const get = (activityAssignmentId, callback) => ({
    type: ACTIVITY_ASSIGNMENTS_BY_ID,
    payload: { activityAssignmentId, callback },
});

export const getByStudent = (studentId, callback) => ({
    type: ACTIVITY_ASSIGNMENTS_BY_STUDENT,
    payload: { studentId, callback },
});

export const submit = (assignmentId, response) => ({
    type: ACTIVITY_ASSIGNMENTS_SUBMIT,
    payload: {assignmentId, response}
});