export const CHAT_GET_RESPONSE = 'CHAT_GET_RESPONSE';
export const CHAT_GET_RESPONSE_PENDING = 'CHAT_GET_RESPONSE_PENDING';
export const CHAT_GET_RESPONSE_FULFILLED = 'CHAT_GET_RESPONSE_FULFILLED';
export const CHAT_GET_RESPONSE_REJECTED = 'CHAT_GET_RESPONSE_REJECTED';

export const CHAT_GET_ESSAY_TITLES = 'CHAT_GET_ESSAY_TITLES';
export const CHAT_GET_ESSAY_TITLES_PENDING = 'CHAT_GET_ESSAY_TITLES_PENDING';
export const CHAT_GET_ESSAY_TITLES_FULFILLED = 'CHAT_GET_ESSAY_TITLES_FULFILLED';
export const CHAT_GET_ESSAY_TITLES_REJECTED = 'CHAT_GET_ESSAY_TITLES_REJECTED';

export const CHAT_VALIDATE_ESSAY = 'CHAT_VALIDATE_ESSAY';
export const CHAT_VALIDATE_ESSAY_PENDING = 'CHAT_VALIDATE_ESSAY_PENDING';
export const CHAT_VALIDATE_ESSAY_FULFILLED = 'CHAT_VALIDATE_ESSAY_FULFILLED';
export const CHAT_VALIDATE_ESSAY_REJECTED = 'CHAT_VALIDATE_ESSAY_REJECTED';

export const list = (chatPayload) => ({
    type: CHAT_GET_RESPONSE,
    payload: {chatPayload}
});

export const getTitles = () => ({
    type: CHAT_GET_ESSAY_TITLES
});

export const validate = (essay) => ({
    type: CHAT_VALIDATE_ESSAY,
    payload: {essay}
});