export const STUDENTS_LIST = 'STUDENTS_LIST';
export const STUDENTS_LIST_PENDING = 'STUDENTS_LIST_PENDING';
export const STUDENTS_LIST_FULFILLED = 'STUDENTS_LIST_FULFILLED';
export const STUDENTS_LIST_REJECTED = 'STUDENTS_LIST_REJECTED';

export const STUDENTS_GET = 'STUDENTS_GET';
export const STUDENTS_GET_PENDING = 'STUDENTS_GET_PENDING';
export const STUDENTS_GET_FULFILLED = 'STUDENTS_GET_FULFILLED';
export const STUDENTS_GET_REJECTED = 'STUDENTS_GET_REJECTED';

export const STUDENTS_GET_BY_PARENT_LIST = 'STUDENTS_GET_BY_PARENT_LIST';
export const STUDENTS_GET_BY_PARENT_LIST_PENDING = 'STUDENTS_GET_BY_PARENT_LIST_PENDING';
export const STUDENTS_GET_BY_PARENT_LIST_FULFILLED = 'STUDENTS_GET_BY_PARENT_LIST_FULFILLED';
export const STUDENTS_GET_BY_PARENT_LIST_REJECTED = 'STUDENTS_GET_BY_PARENT_LIST_REJECTED';

export const STUDENTS_ERROR_RESET = 'STUDENTS_ERROR_RESET';
export const STUDENTS_RESET = 'STUDENTS_RESET';

export const get = (studentId, callback) => ({
    type: STUDENTS_GET,
    payload: { studentId, callback },
});

export const getStudentByParent = (parentId, callback) => ({
    type: STUDENTS_GET_BY_PARENT_LIST,
    payload: { parentId, callback },
});
